language: node_js
node_js:
- 10.15.2
cache:
  directories:
    - node_modules
#before_install:
#  - export CHROME_BIN=chromium-browser
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
install:
- npm install
- mkdir ../locale
- touch ../locale/frontend.pot
script:
- npm run ci
notifications:
  email:
  - riot@c-base.org
